name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Docker registry
      run: echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login ghcr.io -u t0nyz0 --password-stdin

    - name: Build Docker image
      run: docker build . -t ghcr.io/t0nyz0/bambuboard-h2d:latest --label "org.opencontainers.image.source=https://github.com/t0nyz0/BambuBoard-H2D"

    - name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/t0nyz0/bambuboard-h2d:latest

    - name: Make Docker image public automatically
      run: |
        curl -X PATCH https://api.github.com/repos/t0nyz0/BambuBoard-H2D/packages/container/bambuboard-h2d/visibility \
        -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        -d '{"visibility":"public"}'
